intentionet/netconan

- setup.cfg
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/52)
> Add coverage data to netconan

- README.rst
- netconan/anonymize_files.py
- netconan/netconan.py
- netconan/sensitive_item_removal.py
- tests/test_sensitive_item_removal.py
* Added AS number anonymization option
* Updated readme
* Added tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/53)
> Added AS number anonymization

- README.rst
- netconan/anonymize_files.py
- netconan/sensitive_item_removal.py
- tests/test_sensitive_item_removal.py
* Only match stand-alone AS numbers (surrounded by non-digits)
* Replace all-at-once instead of looping
* Test updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/54)
> Only replace stand-alone AS numbers

- netconan/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/55)
> Prepare for release 0.2.0: Updating version number

- netconan/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/63)
> Prepare for release 0.4.0: Updating version number

- netconan/default_pwd_regexes.py
- netconan/sensitive_item_removal.py
- tests/unit/test_sensitive_item_removal.py
* Added new password regexes
* Added more test cases
Fixes #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/67)
> Support for more password lines

- netconan/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/69)
> Prepare for release 0.5.0: Updating version number

- netconan/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/71)
> Prepare for release 0.6.0: Updating version number

- README.rst
- netconan/anonymize_files.py
- netconan/netconan.py
- tests/end_to_end/test_end_to_end.py
Add ability for users to specify reserved words
Fixes #73
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/76)
> Add user specified reserved words

- netconan/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/77)
> Prepare for release 0.7.0: Updating version number

- netconan/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/80)
> Prepare for release 0.8.0: Updating version number

- netconan/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/82)
> Prepare for release 0.8.1: Updating version number

- netconan/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/92)
> Prepare for release 0.8.2: Updating version number

- netconan/anonymize_files.py
- tests/unit/test_anonymize_files.py
Extend file list instead of overwriting it when processing input directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/93)
> Fix recursive directory processing

- netconan/__version__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/94)
> Prepare for release 0.9.0: Updating version number

- netconan/anonymize_files.py
- setup.py
- tests/unit/test_anonymize_files.py
Continue anonymizing if individual file(s) error out
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/97)
> Skip errored files

- netconan/ip_anonymization.py
- tests/unit/test_ip_anonymization.py
Make ip address pattern more strict to skip trying to anonymize bad addresses (e.g. skip `1.2.333.4`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/96)
> Make ip address pattern more strict

- tests/unit/test_as_number_anonymization.py
- tests/unit/test_sensitive_item_removal.py
Split AS number tests into separate file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/106)
> Reorganize anonymization test file

- netconan/netconan.py
- tests/end_to_end/test_end_to_end.py
Add warning and exit when no anonymization args are specified.
Fixes https://github.com/intentionet/netconan/issues/95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/110)
> Add warning and exit when no anonymization args are specified

- netconan/__version__.py
Update master version number after `0.10.0` release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/114)
> Update master version number

- README.rst
- netconan/netconan.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/118)
> Update help for -c argument

- setup.py
Use `Python2` compatible `pytest`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/121)
> Use Python2-compatible pytest

- setup.py
Use [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) for conditional dependencies instead of checking `version_info` in `setup.py`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/127)
> Use environment markers for conditional dependencies

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/128)
> Use environment markers for conditional dependencies (#127)

- netconan/sensitive_item_removal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/147)
> delete unused function

- netconan/default_pwd_regexes.py
- tests/unit/test_sensitive_item_removal.py
Fix #151.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/152)
> fortinet: add password ENC line

- .pre-commit-config.yaml
- netconan/anonymize_files.py
- netconan/default_pwd_regexes.py
- netconan/ip_anonymization.py
- netconan/netconan.py
- netconan/sensitive_item_removal.py
- setup.cfg
- setup.py
- tests/end_to_end/test_end_to_end.py
- tests/unit/test_anonymize_files.py
- tests/unit/test_as_number_anonymization.py
- tests/unit/test_ip_anonymization.py
- tests/unit/test_parse_args.py
- tests/unit/test_sensitive_item_removal.py
- tools/generate_reserved_tokens.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/154)
> add pre-commit, run it

- netconan/default_pwd_regexes.py
- tests/unit/test_sensitive_item_removal.py
Also expand password and pksecret to unencrypted passwords.
Fix #157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/158)
> fortinet: add detection for pksecret secrets

- netconan/ip_anonymization.py
- tests/end_to_end/test_end_to_end.py
- tests/unit/test_ip_anonymization.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/160)
> netconan: fix deanonymize and test

- .pre-commit-config.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/161)
> pre-commmit: add flake8

- netconan/default_pwd_regexes.py
- tests/unit/test_sensitive_item_removal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/162)
> add more Arista and NX-OS password regexes

- netconan/ip_anonymization.py
- tests/unit/test_ip_anonymization.py
Fixes https://github.com/intentionet/netconan/issues/164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/165)
> Fix `-d` (ip-map-dump) when preserving host bits

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/169)
> travis: retire 3.5, add up to 3.9

- .travis.yml
- netconan/ip_anonymization.py
- netconan/sensitive_item_removal.py
- setup.py
- tests/end_to_end/test_end_to_end.py
- tests/unit/test_ip_anonymization.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/174)
> netconan: require python 3.7+

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/175)
> use setup.py python_requires to indicate required version

- .pre-commit-config.yaml
commit-id:b0016fa5
---
**Stack**:
- #183
- #182
- #179
- #180
- #181 ⬅
> pre-commit: upgrade black to one that works with newer click

- setup.py
commit-id:7359cd6d
---
**Stack**:
- #183
- #182
- #179
- #180 ⬅
> upgrade pytest

- .github/workflows/test.yml
commit-id:8e8d6fbf
---
**Stack**:
- #183
- #182
- #179 ⬅
> CI: attempt to add github actions

- setup.py
It's now tested after the switch to GitHub actions.
commit-id:430f9254
> netconan: advertise 3.10 support

- .pre-commit-config.yaml
**Stack**:
- #188
- #187 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/187)
> flake8: fix URL

- .github/workflows/test.yml
**Stack**:
- #189 ⬅
- #188
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/189)
> remove 3.7 support

- .github/workflows/test.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/188)
> test: run for PRs too

- netconan/default_pwd_regexes.py
- tests/unit/test_sensitive_item_removal.py
**Stack**:
- #191
- #190 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/190)
> pre-commit run --all-files

- .pre-commit-config.yaml
**Stack**:
- #192 ⬅
- #191
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/192)
> pre-commit: switch to https mirror

- .github/workflows/pre-commit-checks.yaml
- .github/workflows/test.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/191)
> workflows: switch to separate, full pre-commit check

- .github/workflows/pre-commit-checks.yaml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- netconan/__init__.py
- netconan/anonymize_files.py
- netconan/default_pwd_regexes.py
- netconan/ip_anonymization.py
- netconan/netconan.py
- netconan/sensitive_item_removal.py
- setup.py
- tests/end_to_end/test_end_to_end.py
- tests/unit/test_anonymize_files.py
- tests/unit/test_as_number_anonymization.py
- tests/unit/test_ip_anonymization.py
- tests/unit/test_parse_args.py
- tests/unit/test_sensitive_item_removal.py
- tools/generate_reserved_tokens.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/194)
> Upgrade a bunch of things, add Python 3.11-3.12

- .github/workflows/test.yml
- setup.py
**Stack**:
- #199
- #197
- #198 ⬅
> setup.py: move tests_require to extra test

- .spr.yml
**Stack**:
- #199
- #197 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/197)
> add git-spr config

- .github/workflows/test.yml
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/199)
> python: remove 3.8 EOL add 3.13 newest

- netconan/sensitive_item_removal.py
- tests/unit/test_sensitive_item_removal.py
This change will find Pre-Shared keys in the VpnConnection.json file in both the JSON body and the CustomerGateway xml and anonymize them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/196)
> Striping Pre-Shared keys from AWS configs.

- netconan/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/202)
> start the 0.14.0.dev version

- DEVELOPMENT.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/203)
> add brief instructions on development

- .github/workflows/publish.yml
- DEVELOPMENT.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/204)
> Draft a test pypi publishing workflow

- .github/workflows/publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/205)
> Working, tested publish script for test.pypi.org

- netconan/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/210)
> Bump to 0.15.0.dev

- DEVELOPMENT.rst
Prefer the GitHub Action
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/211)
> Remove old releasing instructions
