intentionet/netconan

netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
Updated sensitive item removal to preserve leading and trailing whitespace (preserve more context and readability).
Fixes #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/66)
=> Preserve whitespace

netconan/default_reserved_words.py, netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
* Changed `default_reserved_words` from a list to a set
* Not anonymizing BGP well-known communities
* Not anonymizing reserved words in password lines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/70)
=> More reserved word preservation

netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
Fixed multiple-password-replacement behavior where passwords would be incorrectly left alone if a preceding password were a reserved word.
Fixes #74
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/75)
=> Improve multi-password replacement behavior

netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
Updated snmp community regex in `sensitive_item_removal` to permit additional syntax (well-known BGP and numeric communities in parenthesis, which is [permitted in Cisco XR](https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-0/routing/configuration/guide/rc40xr12k_chapter7.html)).
For example `set community (123:456)` and `set community (no-export)` are no longer anonymized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/79)
=> Update snmp community regex

netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
Fixing two issues here:
* trailing words after communities are no longer grouped with the community/anonymized (e.g. `set community foo trailing text` will now be correctly anonymized to `set community netconanRemoved trailing text` instead of `set community netconanRemoved`)
* snmp communities that start with bgp communities (e.g. `gshutfoo` or `1234foo`) are now correctly identified as such and anonymized
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/81)
=> SNMP community regex update

netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
Add regex to handle alternate snmp-community syntax (`snmp-community` vs `snmp-server community`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/85)
=> Handle additional snmp-community syntax

netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
[Cisco UCS SNMP community syntax](https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/sw/cli/config/guide/2-0/b_UCSM_CLI_Configuration_Guide_2_0/b_UCSM_CLI_Configuration_Guide_2_0_chapter_0110.html) is very similar to [Cisco IOS BGP community syntax](https://www.cisco.com/c/en/us/td/docs/routers/crs/software/crs_r4-1/routing/command/reference/b_routing_cr41crs/b_routing_cr41crs_chapter_01000.html), where `set community blah` may be a sensitive line on one device but not on the other.  There are some clues to when the community name is a BGP community (and therefore is not sensitive), like when it is:
* a well-known community: `gshut`, `internet`, ...
* numeric: `1234`, `123:456`
* using a parameter or `peeras`: `$foo:123`, `$foo:$bar`, `peeras:24`
* a list of values in …
=> Update community regex to ignore more BGP communities

README.rst, netconan/anonymize_files.py, netconan/netconan.py, tests/unit/test_anonymize_files.py
Previously `Netconan` could only anonymize files in the root of the specified input directory.
This PR updates `Netconan` to:
* Allow individual files to be passed in for `input` and `output`
* Recursively process `input` directory
With a dir structure of:
```
anon/
configs/
sensitive1/
cisco.cfg
juniper.cfg
sensitive2/
palo_alto.cfg
```
Now, the following is possible:
* `netconan -i configs/sensitive1/cisco.cfg -o anon/cisco_anon.cfg -p -a`
* anonymizes only the cisco.cfg and saves it at anon/cisco_anon.cfg
* `netconan -i configs -o anon -p -a`
* anonymizes and saves all three files under anon/, preserving original dir structure
Fixes https://github.com/intentionet/netconan/issues/60 and https://github.com/intentionet/netconan/issues/78
---
This change is [<img …
=> Recursively process files and allow individual file inputs

netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
* Preserve leading and trailing context around sensitive lines (e.g. `{`, `;`, ...)
* Note: this err's on the side of preserving too much text if a password legitimately ends in special characters (e.g. if the password is literally `password,"`, the `,"` will not be anonymized)
* Moved reserved word checking inside `anonymize_value`, so it now occurs after extracting enclosing text
* Move around some debug statements and add a little more debug info
* Update enclosing text extraction to check leading and trailing separately
Fixes #102 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/104)
=> Save more context surrounding sensitive lines

netconan/default_pwd_regexes.py, netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
* Update password removal test to be more explicit about expected outputs
* Make sure we're not anonymizing too much or too little
* Split out password removal with extra internal whitespace into its own test
* Fix a regex causing too much to be anonymized
* Add TODO about under-anonymization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/108)
=> Update password removal test

README.rst, netconan/anonymize_files.py, netconan/ip_anonymization.py, netconan/netconan.py, tests/end_to_end/test_end_to_end.py, tests/unit/test_anonymize_files.py, tests/unit/test_ip_anonymization.py
* Preserve private-use IP blocks by default (https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml)
* Add option to anonymize private IP blocks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/112)
=> Preserve private-use IPv4 blocks

setup.py
`regex` is broken (https://bitbucket.org/mrabarnett/mrab-regex/issues/314/import-error-no-module-named), so pinning to last working version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/113)
=> Pin regex version

setup.py
`regex` import issue fixed now (https://bitbucket.org/mrabarnett/mrab-regex/issues/314/import-error-no-module-named)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/115)
=> Unpin regex version

setup.py
[`pydocstyle 4.0.0`](http://www.pydocstyle.org/en/4.0.0/) no longer supports Python2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/123)
=> Pin pydocstyle

setup.py
Pin all dependencies to less than the next major version (except `regex`, where major version isn't well defined, so just use the most-recent working version on `PyPI` and `conda-forge`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/124)
=> Pin all dependencies

setup.py
Only use `enum34` for Python < 3.4
Addresses https://github.com/intentionet/netconan/issues/122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/125)
=> Only use enum34 for Python < 3.4

netconan/ip_anonymization.py, tests/end_to_end/test_end_to_end.py
Fixes a bug where `Netconan` would crash when preserved prefixes were specified in Python2:
`AddressValueError: <prefix> does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/130)
=> Ensure unicode for user-specified preserved-prefixes

README.rst, netconan/anonymize_files.py, netconan/ip_anonymization.py, netconan/netconan.py, tests/end_to_end/test_end_to_end.py, tests/unit/test_ip_anonymization.py
Add option to preserve specified network block(s).
For example, if a user wants to anonymize IPv4 addresses but preserve private-use addresses, they could run:
```
netconan -a -i input_dir/ -o output_dir/ --preserve-private-addresses
```
Or to preserve specific, non-private addresses, user could run something like:
```
netconan -a -i input_dir/ -o output_dir/ --preserve-addresses 11.12.13.14,111.111.0.0/16
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/129)
=> Add option to preserve specified network block

netconan/ip_anonymization.py, netconan/sensitive_item_removal.py, tests/unit/test_ip_anonymization.py
Use Python built-in `re` in place of `regex` in several places.  This mostly involves replacing variable-length lookbehinds (not supported by `re`) with combinations of fixed-length lookbehinds.
Sensitive line anonymization (i.e. password regexes) will require more/alternative work due to extensive use of non-trivial variable-length lookbehinds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/132)
=> Use `re` in place of `regex`

.travis/build.sh, setup.py
`zipp` 2.2 does not work with Python 3.5, so install 2.1 for Python 3.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/136)
=> Fix CI install

.travis/build.sh, setup.py
CI is having dependency resolution issues w/ `tests_require` in `python2.7` (e.g. [see this build](https://travis-ci.com/github/intentionet/netconan/jobs/348656177)):
* Not installing `python2` compatible version of dependencies (e.g. installing `pyparsing` `3.0.0a1`, which is `python3` only)
---
This PR explicitly enumerates test dependencies in a `test` section in `extras_require` and bumps the required version of `pytest` (required by new `pytest-cov`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/140)
=> Fix dependency resolution issues

netconan/sensitive_item_removal.py, tests/end_to_end/test_end_to_end.py, tests/unit/test_anonymize_files.py
We made sensitive words case-insensitive so that users don't have to know
in advance all possible cases in which they appear. E.g., Intentionet, intentionet.
However, despite matching any case, we should anonymize each case separately. This will
leak less information if for some reason one occurrence is guessable, otherws will not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/148)
=> netconan: anonymize sensitive words in a case-sensitive way

README.rst, netconan/anonymize_files.py, netconan/ip_anonymization.py, netconan/netconan.py, tests/end_to_end/test_end_to_end.py, tests/unit/test_ip_anonymization.py
IP Anonymization breaks important structure when it anonymizes IP address
inside of interface addresses or NAT pools. For example, a link 10.0.0.1/30
and 10.0.0.2/30 will be broken 3/4 of the time because one of the IPs may
get anonymized to 10.0.0.0 (the network address) or 10.0.0.3 (the broadcast
address).
Similarly, a NAT pool like 10.0.0.0 to 10.0.0.5 might get anonymized to
10.0.0.7 to 10.0.0.1, which is invalid (backwards) and would have a different
size if we flipped the end points. This can be especially problematic for
Static NAT if we map both start and end IPs: 1.1.1.1-1.1.1.5 and 2.2.2.1-2.2.2.5.
There is no guarantee that after anonymization, the pools will be the same size!
To fix this, users can use the --preserve-host-bits B flag to prevent
netconan from anonymizing the …
=> netconan: preserve host bits

netconan/ip_anonymization.py, tests/unit/test_ip_anonymization.py
Expand allowed enclosing characters to include `_`
This allows anonymizing things like `object_name_10.10.10.10`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/159)
=> Better IP address detection

setup.py
`ipaddress` is part of the Python standard library since 3.3, so only require it for older versions of Python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/171)
=> Setup: only require `ipaddress` for older python versions

setup.py
They bumped to 1.0.0 immediately after the version
we used, without breaking anything.
commit-id:106c0995
---
**Stack**:
- #185
- #184 ⬅
=> netconan: permit configargparse major version 1

.github/workflows/publish.yml
This is a best practice as recommended https://github.com/marketplace/actions/pypi-publish
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/206)
=> Split build and publish into 2 jobs

netconan/sensitive_item_removal.py, tests/unit/test_sensitive_item_removal.py
Refactor password anonymization to match multiple passwords on a single line. This fixes a bug where the two preshared keys in AWS VPNs get replaced with the same value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intentionet/netconan/207)
=> Refactor password anonymization to match multiple passwords.
